Repository openshift-assisted/bug-master-bot, pull requests merged in 2023-08, with the labels that each got.

#17 NO-ISSUE: Fix python version to 3.11
  Dockerfile
Labels: jira/valid-reference, lgtm, size/XS

#21 NO-ISSUE: Add my account as approver
  OWNERS_ALIASES
Labels: jira/valid-reference, do-not-merge/hold, lgtm, size/XS

#20 NO-ISSUE: Use flake8 in lint and reformat the project. Set mak line length to 120
  .flake8
  Makefile
  pyproject.toml
  src/bug_master/async_pool.py
  src/bug_master/bug_master_bot.py
  src/bug_master/channel_config_handler.py
  src/bug_master/channel_message.py
  src/bug_master/commands/__init__.py
  src/bug_master/commands/apply_command.py
  src/bug_master/commands/channel_configuration_command.py
  src/bug_master/commands/command.py
  src/bug_master/commands/command_handler.py
  src/bug_master/commands/filterby_command.py
  src/bug_master/commands/job_info_command.py
  src/bug_master/commands/list_command.py
  src/bug_master/commands/statistics_command.py
  src/bug_master/commands/supported_commands.py
  src/bug_master/consts.py
  src/bug_master/events/event_handler.py
  src/bug_master/events/file_events.py
  src/bug_master/events/message_channel_event.py
  src/bug_master/events/supported_events.py
  src/bug_master/interactive/__init__.py
  src/bug_master/interactive/drop_down_menus/__init__.py
  src/bug_master/interactive/drop_down_menus/days_range_drop_down.py
  src/bug_master/interactive/drop_down_menus/drop_down_interactive.py
  src/bug_master/interactive/drop_down_menus/jobs_drop_down.py
  src/bug_master/interactive/interactive_flow_handler.py
  src/bug_master/interactive/interactive_response.py
  src/bug_master/middleware.py
  src/bug_master/prow_job.py
  src/bug_master/routes.py
  src/bug_master/utils.py
Labels: jira/valid-reference, lgtm, size/XL, approved

#22 MGMT-15576: Increase the number of bug-master replicas in app-sre cluster
  openshift/template.yaml
Labels: jira/valid-reference, lgtm, size/XS, approved
