Repository openshift-assisted/bug-master-bot, pull requests merged in 2024-05, with the labels that each got.

#31 MGMT-17719: Bump aiohttp to 3.9.4 to mitigate CVE-2024-30251
  catalog
  requirements.txt
Labels: jira/valid-reference, lgtm, size/XS, approved

#33 NO-ISSUE: Enable dependabot
  .github/dependabot.yml
Labels: jira/valid-reference, lgtm, size/S, approved

#35 NO-ISSUE: Add support with marking failed steps
  src/bug_master/channel_config_handler.py
  src/bug_master/prow_job.py
Labels: jira/valid-reference, lgtm, size/M, approved
